version: '2'
services:
 db:
   image: mariadb
   environment:
     - MYSQL_ROOT_PASSWORD=thisistorny
     - MYSQL_DATABASE=torny
   ports:
    - "3306:3306"
 web:
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/code
   ports:
     - "8000:8000"
   depends_on:
     - db